language: node_js
node_js:
    - "9"
sudo: false
branches:
    only:
    - master

install:
  - npm install
  - jspm install
  - npm install -g local-web-server

script:
    - "ws > /dev/null &"
    - sleep 3
    - "curl -If http://127.0.0.1:8000"
